Adds tv, watch support

diff --git a/.github/workflows/swift.yml b/.github/workflows/swift.yml
--- a/.github/workflows/swift.yml
+++ b/.github/workflows/swift.yml
@@ -16,9 +16,18 @@ jobs:
       DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
     steps:
       - uses: actions/checkout@v3
-      - name: Test iOS
+      - name: Build iOS
         run: |
           set -o pipefail && xcodebuild test -scheme "Log-Package" -destination "OS=16.2,name=iPhone 14 Pro" -skipPackagePluginValidation | xcpretty
-      - name: Test macOS
+      - name: Build macOS
         run: |
           set -o pipefail && xcodebuild test -scheme "Log-Package" -destination "platform=macOS,arch=arm64" -skipPackagePluginValidation | xcpretty
+      - name: Build macCatalyst
+        run: |
+          set -o pipefail && xcodebuild test -scheme "Log-Package" -destination "platform=macOS,arch=arm64,variant=Mac Catalyst" -skipPackagePluginValidation | xcpretty
+      - name: Build tvOS
+        run: |
+          set -o pipefail && xcodebuild test -scheme "Log-Package" -destination "platform=tvOS Simulator,name=Apple TV 4K (3rd generation)" -skipPackagePluginValidation | xcpretty
+      - name: Build watchOS
+        run: |
+          set -o pipefail && xcodebuild test -scheme "Log-Package" -destination "platform=watchOS Simulator,name=Apple Watch Ultra (49mm)" -skipPackagePluginValidation | xcpretty
