Update GitHub actions

diff --git a/.github/workflows/swift.yml b/.github/workflows/swift.yml
--- a/.github/workflows/swift.yml
+++ b/.github/workflows/swift.yml
@@ -18,16 +18,16 @@ jobs:
       - uses: actions/checkout@v3
       - name: Build iOS
         run: |
-          set -o pipefail && xcodebuild test -scheme "Log-Package" -destination "OS=16.2,name=iPhone 14 Pro" -skipPackagePluginValidation | xcpretty
+          set -o pipefail && xcodebuild test -scheme "Log-Package" -destination "OS=16.4,name=iPhone 14 Pro" -skipPackagePluginValidation | xcbeautify
       - name: Build macOS
         run: |
-          set -o pipefail && xcodebuild test -scheme "Log-Package" -destination "platform=macOS,arch=arm64" -skipPackagePluginValidation | xcpretty
+          set -o pipefail && xcodebuild test -scheme "Log-Package" -destination "platform=macOS,arch=arm64" -skipPackagePluginValidation | xcbeautify
       - name: Build macCatalyst
         run: |
-          set -o pipefail && xcodebuild test -scheme "Log-Package" -destination "platform=macOS,arch=arm64,variant=Mac Catalyst" -skipPackagePluginValidation | xcpretty
+          set -o pipefail && xcodebuild test -scheme "Log-Package" -destination "platform=macOS,arch=arm64,variant=Mac Catalyst" -skipPackagePluginValidation | xcbeautify
       - name: Build tvOS
         run: |
-          set -o pipefail && xcodebuild test -scheme "Log-Package" -destination "platform=tvOS Simulator,name=Apple TV 4K (3rd generation)" -skipPackagePluginValidation | xcpretty
+          set -o pipefail && xcodebuild test -scheme "Log-Package" -destination "platform=tvOS Simulator,name=Apple TV 4K (3rd generation)" -skipPackagePluginValidation | xcbeautify
       - name: Build watchOS
         run: |
-          set -o pipefail && xcodebuild test -scheme "Log-Package" -destination "platform=watchOS Simulator,name=Apple Watch Ultra (49mm)" -skipPackagePluginValidation | xcpretty
+          set -o pipefail && xcodebuild test -scheme "Log-Package" -destination "platform=watchOS Simulator,name=Apple Watch Ultra (49mm)" -skipPackagePluginValidation | xcbeautify
